#!/bin/bash

echo "Compiling markdown files ..."

regex="(.*)\.md"
list=$(git diff --cached --name-only --diff-filter=ACM)

while read -r line; do
	if [[ $line =~ $regex ]]; then
		file=${BASH_REMATCH[1]}

		pandoc $file.md -o $file.pdf
		# compile markdown files to pdf
		git add $file.pdf
		# add compiled files to commit
		echo "$file.md -> $file.pdf"
	fi
done <<< "$list"

echo "Finished Compiling and added files to Commit!"

exit 0
